import { Check, Plus, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import type { ExerciseSet } from '@/types'

type Props = { exerciseId: string; sets: ExerciseSet[]; onAdd: () => void; onUpdate: (setId: string, updates: Partial<ExerciseSet>) => void; onToggle: (setId: string) => void; onRemove: (setId: string) => void }

export function ExerciseSetTable({ exerciseId, sets, onAdd, onUpdate, onToggle, onRemove }: Props) {
  return <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[32rem] text-left text-xs"><thead className="text-slate-500"><tr><th className="px-2 py-2">Set</th><th className="px-2 py-2">Weight kg</th><th className="px-2 py-2">Reps</th><th className="px-2 py-2">RPE</th><th className="px-2 py-2">Done</th><th className="px-2 py-2" /></tr></thead><tbody>{sets.map((set) => <tr key={`${exerciseId}-${set.setId}`} className="border-t border-slate-800"><td className="px-2 py-2 text-slate-400">{set.setNumber}</td><td className="px-2 py-2"><input type="number" min="0" step="any" value={set.weightKg} onChange={(event) => onUpdate(set.setId, { weightKg: Number(event.target.value) })} className="w-20 rounded border border-slate-700 bg-slate-950 px-2 py-1 text-slate-100" /></td><td className="px-2 py-2"><input type="number" min="0" value={set.reps} onChange={(event) => onUpdate(set.setId, { reps: Number(event.target.value) })} className="w-16 rounded border border-slate-700 bg-slate-950 px-2 py-1 text-slate-100" /></td><td className="px-2 py-2"><input type="number" min="1" max="10" step="any" value={set.rpe ?? ''} onChange={(event) => onUpdate(set.setId, { rpe: event.target.value ? Number(event.target.value) : undefined })} className="w-16 rounded border border-slate-700 bg-slate-950 px-2 py-1 text-slate-100" /></td><td className="px-2 py-2"><button type="button" onClick={() => onToggle(set.setId)} aria-label={set.isCompleted ? 'Mark set incomplete' : 'Mark set complete'} className={set.isCompleted ? 'text-emerald-300' : 'text-slate-500'}><Check className="h-5 w-5" /></button></td><td className="px-2 py-2"><button type="button" onClick={() => onRemove(set.setId)} aria-label="Remove set" className="text-slate-500 hover:text-rose-300"><Trash2 className="h-4 w-4" /></button></td></tr>)}</tbody></table><Button type="button" size="sm" variant="ghost" className="mt-2" onClick={onAdd}><Plus className="mr-2 h-4 w-4" />Add set</Button></div>
}
